import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { appendFile, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ACTIVE_GAP, ACTIVITY_EVENTS, activityOf, feedLine, findTranscript, newTally, patchFiles, readActivity, toolText } from "./activity";
import { projectFolder } from "./sessions";

const S1 = "11111111-2222-4333-8444-555555555555";
const S2 = "22222222-3333-4444-8555-666666666666";
const S3 = "33333333-4444-4555-8666-777777777777";
const S4 = "44444444-5555-4666-8777-888888888888";

const at = (sec: number) => new Date(Date.UTC(2026, 9, 6, 10, 0, sec)).toISOString();
const ms = (sec: number) => Date.UTC(2026, 9, 6, 10, 0, sec);
const line = (rec: unknown) => JSON.stringify(rec);

/* ---------- Claude Code ---------- */

const user = (sec: number, content: unknown, extra: Record<string, unknown> = {}) =>
  line({ type: "user", timestamp: at(sec), message: { role: "user", content }, ...extra });
const assistant = (sec: number, id: string, content: unknown[], usage: Record<string, number> | null = null, model = "claude-opus-5-5") =>
  line({ type: "assistant", timestamp: at(sec), message: { id, role: "assistant", model, content, ...(usage ? { usage } : {}) } });

function claude(lines: string[]) {
  const t = newTally("claude");
  for (const l of lines) feedLine(t, l);
  return activityOf(t, S1, 100, 200);
}

describe("a Claude Code transcript", () => {
  test("counts typed prompts, not tool results, meta lines or the harness's own blocks", () => {
    const a = claude([
      user(0, "fix the login bug"),
      user(1, "<command-name>/clear</command-name>"),
      user(2, "Caveat: the messages below were generated by the user while running local commands."),
      user(3, [{ type: "text", text: "[Request interrupted by user]" }]),
      user(4, "a reminder", { isMeta: true }),
      user(5, [{ type: "text", text: "and  the\nsignup one" }, { type: "text", text: "second part" }]),
      user(6, [{ type: "tool_result", tool_use_id: "x", content: "ok" }]),
    ]);
    expect(a.prompts).toBe(2);
    expect(a.firstPrompt).toBe("fix the login bug");
    expect(a.lastPrompt).toBe("and the signup one");
    expect(a.events.map((e) => e.kind)).toEqual(["prompt", "prompt"]);
  });

  test("tools by use, files a tool wrote, failures named by their tool", () => {
    const a = claude([
      assistant(0, "m1", [{ type: "tool_use", id: "t1", name: "Bash", input: { command: "bun test", description: "Run tests" } }]),
      user(1, [{ type: "tool_result", tool_use_id: "t1", is_error: true, content: "Exit code 1\n3 failed" }]),
      assistant(2, "m2", [{ type: "tool_use", id: "t2", name: "Edit", input: { file_path: "/r/a.ts", old_string: "x", new_string: "y" } }]),
      assistant(3, "m3", [{ type: "tool_use", id: "t3", name: "Write", input: { file_path: "/r/b.ts", content: "" } }]),
      assistant(4, "m4", [{ type: "tool_use", id: "t4", name: "Edit", input: { file_path: "/r/a.ts", old_string: "y", new_string: "z" } }]),
      assistant(5, "m5", [{ type: "tool_use", id: "t5", name: "Read", input: { file_path: "/r/c.ts" } }]),
      assistant(6, "m6", [{ type: "tool_use", id: "t6", name: "Bash", input: { command: "git status" } }]),
    ]);
    expect(a.toolCalls).toBe(6);
    expect(a.tools).toEqual([
      { name: "Bash", count: 2 },
      { name: "Edit", count: 2 },
      { name: "Read", count: 1 },
      { name: "Write", count: 1 },
    ]);
    // a Read touches nothing; a file edited again moves to the front
    expect(a.files).toEqual(["/r/a.ts", "/r/b.ts"]);
    expect(a.filesTouched).toBe(2);
    expect(a.toolErrors).toBe(1);
    expect(a.events[1]).toEqual({ at: ms(1), kind: "error", tool: "Bash", text: "Exit code 1 3 failed" });
    expect(a.events[0]?.text).toBe("bun test");
  });

  test("a message's usage counts once, the latest of its blocks", () => {
    const a = claude([
      assistant(0, "m1", [{ type: "thinking", thinking: "…" }], { input_tokens: 5, output_tokens: 10, cache_read_input_tokens: 100, cache_creation_input_tokens: 20 }),
      assistant(1, "m1", [{ type: "text", text: "Looking." }], { input_tokens: 5, output_tokens: 30, cache_read_input_tokens: 100, cache_creation_input_tokens: 20 }),
      assistant(2, "m2", [{ type: "text", text: "Done." }], { input_tokens: 1, output_tokens: 7, cache_read_input_tokens: 400, cache_creation_input_tokens: 0 }),
      assistant(3, "m3", [{ type: "text", text: "x" }], null, "<synthetic>"),
    ]);
    expect(a.tokens).toEqual({ input: 6, output: 37, cacheRead: 500, cacheWrite: 20 });
    expect(a.models).toEqual(["claude-opus-5-5"]);
    expect(a.lastReply).toBe("x");
  });

  test("its title, last prompt and cost records, the latest of each standing", () => {
    const a = claude([
      line({ type: "summary", summary: "an old summary" }),
      line({ type: "agent-name", agentName: "Login fixes" }),
      line({ type: "ai-title", aiTitle: "Login bug" }),
      line({ type: "ai-title", aiTitle: "Login and signup bugs" }),
      line({ type: "last-prompt", lastPrompt: "ship it" }),
      line({ type: "cost-state", totalCostUSD: 1.25, totalLinesAdded: 40, totalLinesRemoved: 3 }),
    ]);
    expect(a.title).toBe("Login and signup bugs");
    // no prompt read from the file: the record's stands in
    expect(a.lastPrompt).toBe("ship it");
    expect(a.prompts).toBe(0);
    expect([a.costUsd, a.linesAdded, a.linesRemoved]).toEqual([1.25, 40, 3]);
    expect(claude([line({ type: "summary", summary: "only a summary" })]).title).toBe("only a summary");
  });

  test("busy time adds the gaps under ACTIVE_GAP, and a pause adds nothing", () => {
    const t = newTally("claude");
    feedLine(t, user(0, "go"));
    feedLine(t, assistant(30, "m1", [{ type: "text", text: "on it" }]));
    feedLine(t, assistant(90, "m2", [{ type: "text", text: "done" }]));
    // an hour later
    feedLine(t, user(3690, "next"));
    feedLine(t, assistant(3700, "m3", [{ type: "text", text: "ok" }]));
    const a = activityOf(t, S1, 0, 0);
    expect(a.activeMs).toBe(100_000);
    expect(a.firstAt).toBe(ms(0));
    expect(a.lastAt).toBe(ms(3700));
    expect(ACTIVE_GAP).toBeLessThan(3600_000);
  });

  test("a sidechain, a cut line and a stray are passed over", () => {
    const a = claude([
      user(0, "subagent work", { isSidechain: true }),
      '{"type":"user","message":{"content":"cut',
      "not json",
      "[]",
      "",
    ]);
    expect(a.prompts).toBe(0);
    expect(a.firstAt).toBeNull();
  });

  test("keeps the newest events only", () => {
    const lines = Array.from({ length: ACTIVITY_EVENTS * 3 }, (_, i) =>
      assistant(i, `m${i}`, [{ type: "tool_use", id: `t${i}`, name: "Bash", input: { command: `echo ${i}` } }]),
    );
    const a = claude(lines);
    expect(a.events).toHaveLength(ACTIVITY_EVENTS);
    expect(a.events.at(-1)?.text).toBe(`echo ${ACTIVITY_EVENTS * 3 - 1}`);
    expect(a.toolCalls).toBe(ACTIVITY_EVENTS * 3);
  });
});

/* ---------- Codex ---------- */

const ev = (sec: number, payload: unknown) => line({ timestamp: at(sec), type: "event_msg", payload });
const item = (sec: number, payload: unknown) => line({ timestamp: at(sec), type: "response_item", payload });

function codex(lines: string[]) {
  const t = newTally("codex");
  for (const l of lines) feedLine(t, l);
  return activityOf(t, S2, 0, 0);
}

describe("a Codex rollout", () => {
  test("a prompt said as an event and as a completed item counts once", () => {
    const a = codex([
      line({ timestamp: at(0), type: "session_meta", payload: { id: S2, cwd: "/r" } }),
      line({ timestamp: at(0), type: "turn_context", payload: { model: "gpt-6" } }),
      ev(1, { type: "task_started" }),
      ev(1, { type: "user_message", message: "add a test" }),
      ev(1, { type: "item_completed", item: { type: "UserMessage", content: [{ type: "text", text: "add a test" }] } }),
      item(1, { type: "message", role: "user", content: [{ type: "input_text", text: "add a test" }] }),
      ev(9, { type: "agent_message", message: "Added it." }),
      ev(9, { type: "item_completed", item: { type: "AgentMessage", content: [{ type: "Text", text: "Added it." }] } }),
      ev(9, { type: "task_complete", last_agent_message: "Added it." }),
      // the same words much later are a new prompt
      ev(60, { type: "user_message", message: "add a test" }),
    ]);
    expect(a.prompts).toBe(2);
    expect(a.lastReply).toBe("Added it.");
    expect(a.models).toEqual(["gpt-6"]);
    expect(a.events.map((e) => e.kind)).toEqual(["prompt", "reply", "prompt"]);
  });

  test("tool calls of every shape, and the files a patch names", () => {
    const a = codex([
      item(1, { type: "function_call", name: "shell", arguments: JSON.stringify({ command: ["bash", "-lc", "ls -la"] }), call_id: "c1" }),
      item(2, { type: "custom_tool_call", name: "exec", input: 'text(await tools.exec_command({cmd:"rg \\"todo\\" src"}));', call_id: "c2" }),
      item(3, { type: "custom_tool_call", name: "apply_patch", input: "*** Begin Patch\n*** Update File: src/a.ts\n@@\n-x\n+y\n*** Add File: src/b.ts\n+z\n*** End Patch" }),
      item(4, { type: "local_shell_call", action: { command: ["git", "status"] } }),
      item(5, { type: "web_search_call", action: { query: "bun test docs" } }),
      item(6, { type: "function_call", name: "apply_patch", arguments: JSON.stringify({ input: "*** Begin Patch\n*** Delete File: old.ts\n*** End Patch" }) }),
      item(7, { type: "custom_tool_call", name: "exec", input: "text(await tools.write_stdin({session_id:5,chars:\"\"}));" }),
    ]);
    expect(a.toolCalls).toBe(7);
    expect(a.events.map((e) => e.text)).toEqual(["ls -la", 'rg "todo" src', "src/a.ts, src/b.ts", "git status", "bun test docs", "old.ts", "write_stdin"]);
    expect(a.files).toEqual(["old.ts", "src/b.ts", "src/a.ts"]);
  });

  test("its running token total stands, cached input apart", () => {
    const a = codex([
      ev(1, { type: "token_count", info: { total_token_usage: { input_tokens: 100, cached_input_tokens: 60, output_tokens: 5 } } }),
      ev(2, { type: "token_count", info: { total_token_usage: { input_tokens: 300, cached_input_tokens: 200, output_tokens: 20 } } }),
      ev(3, { type: "token_count", info: null }),
    ]);
    expect(a.tokens).toEqual({ input: 100, output: 20, cacheRead: 200, cacheWrite: 0 });
  });
});

describe("toolText and patchFiles", () => {
  test("pick the line a person reads", () => {
    expect(toolText("Grep", { pattern: "TODO", path: "src" })).toBe("TODO");
    expect(toolText("LS", { path: "src" })).toBe("src");
    expect(toolText("WebFetch", { url: "https://x.dev", prompt: "read" })).toBe("https://x.dev");
    expect(toolText("Task", { description: "Explore auth", prompt: "…" })).toBe("Explore auth");
    expect(toolText("Odd", { n: 1 })).toBe("Odd");
    expect(toolText("Odd", null)).toBe("Odd");
    expect(toolText("Bash", { command: "a".repeat(400) })).toHaveLength(160);
  });
  test("a patch's files, each once", () => {
    expect(patchFiles("*** Update File: a\n*** Update File: a\n*** Add File: b c\n")).toEqual(["a", "b c"]);
    expect(patchFiles("no patch here")).toEqual([]);
  });
});

/* ---------- the files ---------- */

describe("finding and reading a transcript", () => {
  let scratch: string;
  let claudeHome: string;
  let codexHome: string;
  beforeAll(async () => {
    scratch = await mkdtemp(join(tmpdir(), "canopy-activity-"));
    claudeHome = join(scratch, "claude");
    codexHome = join(scratch, "codex");
  });
  afterAll(async () => {
    await rm(scratch, { recursive: true, force: true });
  });

  test("Claude's under its cwd's folder, else under any folder; Codex's by the id its name ends in", async () => {
    const homes = { claude: claudeHome, codex: codexHome };
    const mine = join(claudeHome, "projects", projectFolder("/dev/app"));
    const other = join(claudeHome, "projects", "-a-shortened-name-1a2b");
    await mkdir(mine, { recursive: true });
    await mkdir(other, { recursive: true });
    await writeFile(join(mine, `${S1}.jsonl`), "");
    await writeFile(join(other, `${S2}.jsonl`), "");
    expect(await findTranscript("claude", S1, "/dev/app", homes)).toBe(join(mine, `${S1}.jsonl`));
    expect(await findTranscript("claude", S2, "/dev/app", homes)).toBe(join(other, `${S2}.jsonl`));
    expect(await findTranscript("claude", S3, "/dev/app", homes)).toBeNull();
    // a path is never a session
    expect(await findTranscript("claude", "../../etc/passwd", "/dev/app", homes)).toBeNull();

    const now = new Date(2026, 9, 6, 12);
    const day = join(codexHome, "sessions", "2026", "10", "05");
    await mkdir(day, { recursive: true });
    await writeFile(join(day, `rollout-2026-10-05T09-00-00-${S3}.jsonl`), "");
    expect(await findTranscript("codex", S3, "", homes, now)).toBe(join(day, `rollout-2026-10-05T09-00-00-${S3}.jsonl`));
    expect(await findTranscript("codex", S1, "", homes, now)).toBeNull();
  });

  test("reads on from where it stopped, a cut last line once it is whole, and a rewritten file anew", async () => {
    const homes = { claude: claudeHome };
    const dir = join(claudeHome, "projects", projectFolder("/dev/inc"));
    const file = join(dir, `${S4}.jsonl`);
    await mkdir(join(dir, S4, "subagents"), { recursive: true });
    await writeFile(join(dir, S4, "subagents", "agent-a1.jsonl"), "");
    await writeFile(file, `${user(0, "one")}\n`);
    expect((await readActivity("claude", S4, "/dev/inc", homes))?.prompts).toBe(1);

    const cut = user(5, "two");
    await appendFile(file, cut.slice(0, 20));
    expect((await readActivity("claude", S4, "/dev/inc", homes))?.prompts).toBe(1);
    await appendFile(file, `${cut.slice(20)}\n${user(9, "three")}\n`);
    const a = await readActivity("claude", S4, "/dev/inc", homes);
    expect(a?.prompts).toBe(3);
    expect(a?.lastPrompt).toBe("three");
    expect(a?.subagents).toBe(1);

    // two readings at once feed the tally once
    await appendFile(file, `${user(12, "four")}\n`);
    const [x, y] = await Promise.all([readActivity("claude", S4, "/dev/inc", homes), readActivity("claude", S4, "/dev/inc", homes)]);
    expect([x?.prompts, y?.prompts]).toEqual([4, 4]);

    await writeFile(file, `${user(20, "fresh")}\n`);
    const b = await readActivity("claude", S4, "/dev/inc", homes);
    expect([b?.prompts, b?.firstPrompt]).toEqual([1, "fresh"]);

    await rm(file);
    expect(await readActivity("claude", S4, "/dev/inc", homes)).toBeNull();
    expect(await readActivity("claude", "nope", "/dev/inc", homes)).toBeNull();
  });
});
